---

- name: Install pdftotext on macOS
  ansible.builtin.package:
    name: poppler
    state: present
  register: result
  failed_when: '"installed" not in result.msg and "already installed" not in result.msg and "Package installed" not in result.msg and result.msg != ""'
  when: ansible_os_family == "Darwin"