---

- name: Install opencode on MacOS
  ansible.builtin.package:
    name: opencode
    state: present
  register: result
  failed_when:
    - '"already installed" not in result.msg'
    - '"Package installed" not in result.msg'
    - result.msg != ""
  when: ansible_facts.os_family == 'Darwin'

- name: Ensure opencode config directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.config/opencode"
    state: directory
    mode: '0755'

- name: Soft link opencode configuration
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/opencode.json"
    dest: "{{ ansible_facts.env.HOME }}/.config/opencode/opencode.json"
    force: true
    state: link
