---
- name: Install Temporal CLI (macOS)
  community.general.homebrew:
    name: temporal
    state: present
  when: ansible_facts.os_family == "Darwin"
  become: false

- name: Install Temporal CLI (Arch Linux)
  community.general.pacman:
    name: temporal
    state: present
  when: ansible_facts.os_family == "Archlinux"
  become: true
