---
- name: Install sops on macOS
  community.general.homebrew:
    name: sops
    state: present
  when: ansible_facts.os_family == "Darwin"

- name: Install sops on Arch Linux
  community.general.pacman:
    name: sops
    state: present
  become: true
  when: ansible_facts.os_family == "Archlinux"

- name: Install sops on Ubuntu/Debian
  ansible.builtin.apt:
    name: sops
    state: present
    update_cache: true
  become: true
  when: ansible_facts.os_family == "Debian"
