---

- name: Install Claude Code CLI on MacOS
  ansible.builtin.package:
    name: claude-code
    state: present
  register: result
  failed_when:
    - '"already installed" not in result.msg'
    - '"Package installed" not in result.msg'
    - result.msg != ""
  when: ansible_facts.os_family == 'Darwin'

- name: "Ensure {{ ansible_facts.env.HOME }}/.claude exists"
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.claude"
    state: directory

- name: Soft link Claude Code settings
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/claude-settings.json"
    dest: "{{ ansible_facts.env.HOME }}/.claude/settings.json"
    force: true
    state: link