---

- name: Install htop
  ansible.builtin.package:
    name: htop
    state: present
  become: true
  when: ansible_facts.os_family != "Darwin"

- name: Install htop on macOS
  ansible.builtin.package:
    name: htop
    state: present
  when: ansible_facts.os_family == "Darwin"