---

- name: Install huggingface on MacOS
  ansible.builtin.package:
    name: huggingface-cli
    state: present
  register: result
  failed_when:
    - '"already installed" not in result.msg'
    - '"Package installed" not in result.msg'
    - result.msg != ""
  when: ansible_os_family == 'Darwin'
